{
	"filelist":[
		"/js/json2/json2.min.js",
		"/js/jquery/3.3.1/jquery.min.js",
		"/js/jqueryui/1.12.1/jquery-ui.min.js",
		"/js/react/react.min.js",
		"/js/react/react-dom.min.js",
		"/js/react/react-cookie.0.4.9.min.js",
		"/js/react/ReactRouter/3.0.2/ReactRouter.min.js",
		
		"/js/app/TaoController.jsx",
		"/js/app/TAORoot.jsx",
		"/js/app/TopMenu.jsx",
		"/js/app/LeftBox.jsx",
		"/js/app/TaoContent.jsx",
		"/js/app/TAOindex.jsx",
		"/js/app/LoginTopMenu.jsx",
		"/js/app/OurMission.jsx",
		"/js/app/Footer.jsx",
		"/js/app/LoginMenu.jsx",
		"/js/app/FeatureItem.jsx",
		"/js/app/FeatureList.jsx",
		"/js/app/About.jsx",
	 	"/js/app/AboutContent.jsx",
		"/js/app/Member.jsx",
		"/js/app/Members.jsx"
	]
}